export const categories = [
    { id: '1', name: 'Jawa', image: require('./assets/atributdaerah/jawa.png') },
    { id: '2', name: 'Sumatra', image: require('./assets/atributdaerah/sumatra.png') },
    { id: '3', name: 'Kalimantan', image: require('./assets/atributdaerah/kalimantan.png') },
    { id: '4', name: 'Sulawesi', image: require('./assets/atributdaerah/sulawesi.png') },
    { id: '5', name: 'Papua', image: require('./assets/atributdaerah/papua.png') },
  ];
  
  export const itemList = [
    { id: '1', title: 'Angklung', description: 'Alat musik khas Jawa Barat.', image: require('./assets/alatmusik/jawa/angklung.png') },
    { id: '2', title: 'Gamelan', description: 'Alat musik pukul khas Jawa Tengah.', image: require('./assets/alatmusik/jawa/gamelan.png') },
    { id: '3', title: 'Saluang', description: 'Alat musik musik tiup dari Sumatra Barat.', image: require('./assets/alatmusik/sumatra/saluang.png') },
    { id: '4', title: 'Kolintang', description: 'Alat musik perkusi dari Sulawesi Utara.', image: require('./assets/alatmusik/sulawesi/kolintang.png') },
    { id: '5', title: 'Tifa', description: 'Alat musik pukul khas Papua.', image: require('./assets/alatmusik/papua/tifa.png') },
    { id: '6', title: 'Kendang', description: 'Alat musik pukul khas Jawa Tengah', image: require('./assets/alatmusik/jawa/kendang.png') },
    { id: '7', title: 'Rebab', description: 'Alat musik gesek khas Jawa Tengah', image: require('./assets/alatmusik/jawa/rebab.png') },
    { id: '8', title: 'Siter', description: 'Alat musik petik khas Jawa Tengah', image: require('./assets/alatmusik/jawa/siter.png') },
    { id: '9', title: 'Bonang', description: 'Alat musik pukul khas Jawa Tengah', image: require('./assets/alatmusik/jawa/bonang.png') },
    { id: '10', title: 'Slenthem', description: 'Alat musik pukul khas Jawa Tengah', image: require('./assets/alatmusik/jawa/slenthem.png') },
    { id: '11', title: 'Talempong', description: 'Alat musik tiup khas Sumatra Barat', image: require('./assets/alatmusik/sumatra/talempong.png') },
    { id: '12', title: 'Rebab Piaman', description: 'Alat musik gesek khas Sumatra Barat', image: require('./assets/alatmusik/sumatra/rebab_piaman.png') },
    { id: '13', title: 'Gambus', description: 'Alat musik petik khas Riau', image: require('./assets/alatmusik/sumatra/gambus.png') },
    { id: '14', title: 'Kompang', description: 'Alat musik petik khas Riau', image: require('./assets/alatmusik/sumatra/kompang.png') },
    { id: '15', title: 'Nafiri', description: 'Alat musik tiup khas Riau', image: require('./assets/alatmusik/sumatra/nafiri.png') },
    { id: '16', title: 'Serune Kalee', description: 'Alat musik tiup khas Aceh', image: require('./assets/alatmusik/sumatra/serune_kalee.png') },
    { id: '17', title: 'Babun', description: 'Alat musik pukul khas Kalimantan Utara', image: require('./assets/alatmusik/kalimantan/babun.png') },
    { id: '18', title: 'Garantung', description: 'Alat musik pukul khas Kalimantan Tengah', image: require('./assets/alatmusik/kalimantan/garantung.png') },
    { id: '19', title: 'Kadire', description: 'Alat musik Tiup khas Kalimantan Timur', image: require('./assets/alatmusik/kalimantan/kadire.png') },
    { id: '20', title: 'Kintung', description: 'Alat musik pukul khas Kalimantan Selatan', image: require('./assets/alatmusik/kalimantan/kintung.png') },
    { id: '21', title: 'Panting', description: 'Alat musik petik khas Kalimantan Selatan', image: require('./assets/alatmusik/kalimantan/panting.png') },
    { id: '22', title: 'Sape', description: 'Alat musik petik khas Kalimantan Timur', image: require('./assets/alatmusik/kalimantan/sape.png') },
    { id: '23', title: 'Ganda', description: 'Alat musik pukul khas Sulawesi Tenggara', image: require('./assets/alatmusik/sulawesi/ganda.png') },
    { id: '24', title: 'Kecapi', description: 'Alat musik petik khas Sulawesi Selatan', image: require('./assets/alatmusik/sulawesi/kecapi.png') },
    { id: '25', title: 'Kolintang', description: 'Alat musik pukul khas Sulawesi Utara', image: require('./assets/alatmusik/sulawesi/kolintang.png') },
    { id: '26', title: 'Leko Boko', description: 'Alat musik gesek khas Sulawesi Tenggara', image: require('./assets/alatmusik/sulawesi/leko_boko.png') },
    { id: '27', title: 'PoloPalo', description: 'Alat musik pukul khas Gorontalo', image: require('./assets/alatmusik/sulawesi/polopalo.png') },
    { id: '28', title: 'Salude', description: 'Alat musik petik khas Sulawesi Utara', image: require('./assets/alatmusik/sulawesi/salude.png') },
    { id: '29', title: 'Guoto', description: 'Alat musik petik khas Papua barat', image: require('./assets/alatmusik/papua/guoto.png') },
    { id: '30', title: 'Kecapi Mulut', description: 'Alat musik tiup khas Suku Asmat', image: require('./assets/alatmusik/papua/kecapi_mulut.png') },
    { id: '31', title: 'Pikon', description: 'Alat musik tiup dan di tarik khas Suku Dani', image: require('./assets/alatmusik/papua/pikon.png') },
    { id: '32', title: 'Tifa', description: 'Alat musik pukul khas Papua barat', image: require('./assets/alatmusik/papua/tifa.png') },
    { id: '33', title: 'Triton', description: 'Alat musik tiup khas Papua Selatan', image: require('./assets/alatmusik/papua/triton.png') },
    { id: '34', title: 'Yi', description: 'Alat musik pukul khas Papua pegunungan', image: require('./assets/alatmusik/papua/yi.png') },
  ];
  